name: 'Flipp Global'
description: 'Global action for Flipp workflows'
inputs:
  slack_channel:
    description: 'Slack channel if you want to send notifications'
    required: false
  slack_always:
    description: 'Set to true if you want to send on success as well'
    required: false
  job_status:
    description: "Pass `job.status` - REQUIRED if you want to send a Slack message."
    required: true
  enable_tmate:
    description: "If set, create tmate debug sessions on job failure."
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
  pre: 'dist/setup.js'
  post: 'dist/cleanup.js'
