name: "go-configure"
description: "Set up Go environment for CI build. Sets up Buf if the relevant inputs are provided."

inputs:
  FLIPPCIRCLECIPULLER_REPO_TOKEN:
    description: Flipp circleci repo token
    required: true
  BUF_BUILD_USER:
    description: Buf CI user stored as secret
    required: false
  BUF_BUILD_API_TOKEN:
    description: Buf API token stored as secret
    required: false
  FETCH_DEPTH:
    description: Fetch depth for git checkout
    required: false
    default: 1

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: ${{ inputs.FETCH_DEPTH }}
    - name: Setting up private modules access
      shell: bash
      run: git config --global url."https://${{ inputs.FLIPPCIRCLECIPULLER_REPO_TOKEN }}:x-oauth-basic@github.com/wishabi".insteadOf "https://github.com/wishabi"
    - name: Grab buf version
      if: ${{ hashFiles('.tool-versions') != '' }}
      run: |
        BUF_VERSION=$(awk '/^buf[[:space:]]+/ {print $2}' .tool-versions)
        echo "BUF_VERSION=${BUF_VERSION}" >> $GITHUB_ENV
      shell: bash
    - name: Setting up buf if version is provided
      uses: bufbuild/buf-setup-action@v1
      if: "${{ inputs.BUF_BUILD_API_TOKEN != '' && env.BUF_VERSION != '' }}"
      with:
        github_token: ${{ inputs.FLIPPCIRCLECIPULLER_REPO_TOKEN }}
        buf_user: ${{ inputs.BUF_BUILD_USER }}
        buf_api_token: ${{ inputs.BUF_BUILD_API_TOKEN }}
        version: ${{ env.BUF_VERSION }}
    - name: Setting up buf if version is not provided
      uses: bufbuild/buf-setup-action@v1
      if: "${{ inputs.BUF_BUILD_API_TOKEN != '' && env.BUF_VERSION == '' }}"
      with:
        github_token: ${{ inputs.FLIPPCIRCLECIPULLER_REPO_TOKEN }}
        buf_user: ${{ inputs.BUF_BUILD_USER }}
        buf_api_token: ${{ inputs.BUF_BUILD_API_TOKEN }}
