name: "go-configure"
description: "Set up Go environment for CI build. Sets up Buf if the relevant inputs are provided."

inputs:
  FLIPPCIRCLECIPULLER_REPO_TOKEN:
    description: Flipp circleci repo token
    required: true
  BUF_BUILD_USER:
    description: Buf CI user stored as secret
    required: false
  BUF_BUILD_API_TOKEN:
    description: Buf API token stored as secret
    required: false
  FETCH_DEPTH:
    description: Fetch depth for git checkout
    required: false
    default: 1

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: ${{ inputs.FETCH_DEPTH }}
    - name: Setting up private modules access
      shell: bash
      run: git config --global url."https://${{ inputs.FLIPPCIRCLECIPULLER_REPO_TOKEN }}:x-oauth-basic@github.com/wishabi".insteadOf "https://github.com/wishabi"
    - name: Grab buf and mockery version
      if: ${{ hashFiles('.tool-versions') != '' }}
      run: |
        MOCKERY_VERSION=$(awk '/mockery/ {print $2}' .tool-versions)
        echo "MOCKERY_VERSION=${MOCKERY_VERSION}" >> $GITHUB_ENV
        BUF_VERSION=$(awk '/buf/ {print $2}' .tool-versions)
        echo "BUF_VERSION=${BUF_VERSION}" >> $GITHUB_ENV
    - name: Setting up buf
      uses: bufbuild/buf-setup-action@v1
      if: "${{ inputs.BUF_BUILD_API_TOKEN != '' }}"
      with:
        github_token: ${{ inputs.FLIPPCIRCLECIPULLER_REPO_TOKEN }}
        buf_user: ${{ inputs.BUF_BUILD_USER }}
        buf_api_token: ${{ inputs.BUF_BUILD_API_TOKEN }}
        buf_version: ${{ env.BUF_VERSION }}
    - name: Install mockery
      if: ${{ hashFiles('.mockery.yml') != '' }}
      run: |
        if [ ! -z "${{ env.MOCKERY_VERSION }}" ]; then
          go install github.com/vektra/mockery/v2@{{ env.MOCKERY_VERSION }}
        else
          go install github.com/vektra/mockery/v2
        fi
      shell: bash
