name: 'go-setup'
description: 'Set up Go environment for CI build. Sets up Buf if the relevant inputs are provided.'

inputs:
  FLIPPCIRCLECIPULLER_REPO_TOKEN:
    description: Flipp circleci repo token
    required: true
  BUF_BUILD_USER:
    description: Buf CI user stored as secret
    required: false
  BUF_BUILD_API_TOKEN:
    description: Buf API token stored as secret
    required: false

runs:
  using: 'composite'
  steps:
    - name: Setting up private modules access
      shell: bash
      run: git config --global url."https://${{ inputs.FLIPPCIRCLECIPULLER_REPO_TOKEN }}:x-oauth-basic@github.com/wishabi".insteadOf "https://github.com/wishabi"
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
        check-latest: true
        cache: true
    - name: Setting up buf
      uses: bufbuild/buf-setup-action@v1
      if: "${{ inputs.BUF_BUILD_API_TOKEN != '' }}"
      with:
        buf_user: ${{ inputs.BUF_BUILD_USER }}
        buf_api_token: ${{ inputs.BUF_BUILD_API_TOKEN }}
