name: 'Kafka Schema validation'
description: 'custom GitHub action that runs kafka schema validation'

inputs:
  SLACK_BOT_TOKEN:
    description: secret value
    required: true
  SLACK_CHANNEL:
    description: secret value
    required: true

runs:
  using: "composite"
  steps:
    - name: Restoring workspace from cache
      uses: wishabi/github-actions/cache@v0
    - name: Generate schema validation json
      shell: bash
      run: |
        bundle exec rails g flipp_ruby_kafka:schema_validation
        sudo chown circleci:circleci /var/run/docker.sock
      env: 
        BUNDLE_DEPLOYMENT: true
    - name: Staging Schema validation 
      shell: bash
      run: |
        chmod +x ./deploy/build.sh && ./deploy/build.sh service schema_validation --env=staging
    - name: Production Schema validation
      shell: bash
      run: |
        chmod +x ./deploy/build.sh && ./deploy/build.sh service schema_validation --env=production
