name: 'Kafka Schema validation'
description: 'Custom GitHub action that runs kafka schema validation'

inputs:
  ENV:
    description: Application environment (staging or production)
    required: true

runs:
  using: "composite"
  steps:
    - name: Generate schema validation json
      shell: bash
      run: |
        bundle exec rails g flipp_ruby_kafka:schema_validation
         
        # check if the circeci user exists and update permission. This is needed for non runner-fleet-v2 jobs
        if id "3434" >/dev/null 2>&1; then
            sudo chown circleci:circleci /var/run/docker.sock
        fi
      env: 
        BUNDLE_DEPLOYMENT: true
    - name: Schema validation 
      shell: bash
      run: |
        chmod +x ./deploy/build.sh && ./deploy/build.sh service schema_validation --env=${{ inputs.ENV }}
