name: 'Send Github Action data to Slack workflow'
description: 'custom GitHub action that runs to send data to a Slack workflow'
inputs:
  SLACK_WEBHOOK_URL:
    description: The Slack webhook URL to pass the data to
    required: true

runs:
  using: "composite"
  steps:
    - name: Set BRANCH variable
      id: set-branch
      shell: bash
      run: |
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          BRANCH="${{ github.event.pull_request.head.ref }}"
        else
          BRANCH="${{ github.ref }}"
          BRANCH="${BRANCH#refs/heads/}"
        fi
        echo "BRANCH=${BRANCH}" >> $GITHUB_ENV
    - uses: slackapi/slack-github-action@v1.24.0
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.SLACK_WEBHOOK_URL }}
      with:
        payload: |
          {
            "Job": "<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.job }}>",
            "Repo": "${{ github.repository }}",
            "Branch": "${{ env.BRANCH }}",
            "Event": "${{ github.eventName }}"
          }