name: 'Send Github Action data to Slack workflow'
description: 'custom GitHub action that runs to send data to a Slack workflow'
inputs:
  SLACK_WEBHOOK_URL:
    description: The Slack webhook URL to pass the data to
    required: true
  JOB:
    description: The Github Action job we're notifying about
    required: true
  REPO:
    description: The repo the Github Action is running in
    required: true
  BRANCH:
    description: The branch the Github Action is running on
    required: true
  EVENT:
    description: The event that triggered the Github Action
    required: true


runs:
  using: "composite"
  steps:
    - uses: slackapi/slack-github-action@v1.24.0
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.SLACK_WEBHOOK_URL }}
      with:
        payload: |
          {
            "Job": "${{ inputs.JOB }}",
            "Repo": "${{ inputs.REPO }}",
            "Branch": "${{ inputs.BRANCH }}",
            "Event": "${{ inputs.EVENT }}"
          }