name: 'Ruby bundle install and caching'
description: 'custom GitHub action that runs to setup ruby bundle install and caching'

runs:
  using: "composite"
  steps:
    - name: Bundle cache
      id: bundle-cache
      uses: actions/cache@v3
      with:
        path: vendor/bundle
        key: rails-${{ hashFiles('Gemfile.lock') }}
        restore-keys: rails-${{ hashFiles('Gemfile.lock') }}
    - name: Bundle install
      shell: bash
      run: |
        sudo chmod 1777 -R /home/circleci/.bundle
        bundle config set --local path 'vendor/bundle'
        bundle install --jobs=4
      env: 
        BUNDLE_JOBS: 4
    - name: Caching workspace for deploy jobs
      uses: wishabi/github-actions/cache@v0
