name: 'Kafka Topic and Schema validation shared setup'
description: 'custom GitHub action that runs the shared setup for kafka topic and schema validation'

inputs:
  SLACK_BOT_TOKEN:
    description: secret value
    required: true
  SLACK_CHANNEL:
    description: secret value
    required: true

runs:
  using: "composite"
  steps:
    - name: Bundle cache
      id: bundle-cache
      uses: actions/cache@v3
      with:
        path: vendor/bundle
        key: rails-${{ hashFiles('Gemfile.lock') }}
        restore-keys: rails-${{ hashFiles('Gemfile.lock') }}
    - name: Bundle install
      if: steps.bundle-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        bundle install
      env: 
        BUNDLE_JOBS: 4
        BUNDLE_DEPLOYMENT: true
    - name: Caching workspace for deploy jobs
      uses: wishabi/github-actions/cache@v0
