name: 'Ruby bundle install and caching'
description: 'custom GitHub action that runs to setup ruby bundle install and caching'
inputs:
  USE_CIRCLECI_USER:
      description: Flag that controls whether we're assuming `circleci` user
      required: false
      default: true

runs:
  using: "composite"
  steps:
    - name: Bundle cache
      id: bundle-cache
      uses: actions/cache@v4
      with:
        path: vendor/bundle
        key: rails-${{ hashFiles('Gemfile.lock') }}
        restore-keys: rails-${{ hashFiles('Gemfile.lock') }}
    - name: Set bundle permissions
      if: steps.bundle-cache.outputs.cache-hit != 'true' && inputs.USE_CIRCLECI_USER
      shell: bash
      run: |
        sudo chown -R circleci:circleci /home/circleci/.bundle
    - name: Bundle install
      if: steps.bundle-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        bundle install
      env: 
        BUNDLE_JOBS: 4
        BUNDLE_DEPLOYMENT: true
    - name: Caching workspace for deploy jobs
      uses: wishabi/github-actions/cache@v0
