name: 'Kafka Topic and Schema validation shared setup'
description: 'custom GitHub action that runs the shared setup for kafka topic and schema validation'

inputs:
  SLACK_BOT_TOKEN:
    description: secret value
    required: true
  SLACK_CHANNEL:
    description: secret value
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Flipp global
      uses: wishabi/github-actions@v0.5
      env:
        SLACK_BOT_TOKEN: "${{ inputs.SLACK_BOT_TOKEN }}"
      with:
        slack_channel: "${{inputs.SLACK_CHANNEL }}"
        job_status: "${{ job.status }}"
    - name: Bundle cache
      uses: actions/cache@v3
      with:
        path: vendor/bundle
        key: rails-${{ hashFiles('Gemfile.lock') }}
        restore-keys: rails-
    - run: sudo chmod 1777 -R /home/circleci/.bundle /tmp
      shell: bash
    - name: Bundle install
      shell: bash
      run: |
        bundle config set --local path 'vendor/bundle'
        bundle install --jobs=4
