name: 'publish-to-documentation-hub'
description: 'Publishes an OpenAPI spec to a Stoplight documentation hub'
inputs:
  # Get the CI token from project settings on your Stoplight workspace
  STOPLIGHT_PROJECT_TOKEN:
    description: The Stoplight project token
    required: true
  STOPLIGHT_PROJECT_URL:
    description: The Stoplight project URL
    required: true
  SPEC_ARTIFACT_NAME:
    description: The name of the OpenAPI spec artifact from a previous build step
    required: true

runs:
  using: 'composite'
  steps:
    - name:
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Download OpenAPI spec artifact
      uses: actions/download-artifact@v3
      with:
        name: ${{inputs.SPEC_ARTIFACT_NAME}}
        path: ${{github.workspace}}/specs
    - name: Push files to Stoplight
      shell: bash
      run: |
        npx @stoplight/cli@5 push --ci-token ${{inputs.STOPLIGHT_PROJECT_TOKEN}} --url ${{inputs.STOPLIGHT_PROJECT_URL}} --directory ${{github.workspace}}/specs --branch main
