name: 'Lint - rubocop'
description: 'Lints using rubcop'
runs:
  using: "composite"
  steps:
    - uses: rlespinasse/github-slug-action@v3.x
    - name: Download test result
      uses: actions/download-artifact@v3
      with:
        name: ${{ github.sha }}-test-report.out
        path: ./result/
    - name: execute one-for-all
      shell: bash
      run: |
        aws s3 cp s3://one-for-all/start-one-for-all.sh start-one-for-all.sh
        chmod +x ./start-one-for-all.sh
        ENFORCER_LANGUAGE="ruby" ./start-one-for-all.sh
      env:
        CIRCLE_BRANCH: ${{ env.GITHUB_REF_SLUG }}
        CIRCLE_PROJECT_REPONAME: ${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG }}