name: Smoke Test

description: Run smoke tests

inputs:
  API_URL:
    description: 'Base URL of the API to test against'
    required: false
  FLIPPCIRCLECIPULLER_REPO_TOKEN:
    description: Flipp circleci repo token
    required: true
  GO_VERSION:
    description: Golang version to be used for CI build
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Go
      uses: wishabi/github-actions/go/setup@main
      with:
        GO_VERSION: ${{ inputs.GO_VERSION }}
        FLIPPCIRCLECIPULLER_REPO_TOKEN: ${{ inputs.FLIPPCIRCLECIPULLER_REPO_TOKEN }}
    - name: Run Smoke Tests
      shell: bash
      env:
        API_URL: ${{ inputs.API_URL }}
      run: |
        go test ./tests/smoke --tags=smoke
