name: Smoke Test

description: Run smoke tests

inputs:
  API_URL:
    description: 'Base URL of the API to test against'
    required: false
  FLIPPCIRCLECIPULLER_REPO_TOKEN:
    description: Flipp circleci repo token
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Go
        uses: wishabi/github-actions/go/setup@v0.9
        with:
          GO_VERSION: '1.19'
          FLIPPCIRCLECIPULLER_REPO_TOKEN: ${{ inputs.FLIPPCIRCLECIPULLER_REPO_TOKEN }}
    - name: Run Smoke Tests
      shell: bash
      env:
        API_URL: ${{ inputs.API_URL }}
      run: |
        go test ./tests/smoke --tags=smoke
