name: 'release'
description: 'Creates a Github Release numbered with the latest and the provided commit hash'
inputs:
  GITHUB_TOKEN:
    description: token used to check for existing tags
    required: true

runs:
  using: 'composite'
  steps:
    - name: Clone repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: wemogy/next-version-action@2.0.2
      id: release-version
      with:
        token: ${{ inputs.GITHUB_TOKEN }}
        projects: 'Single'

    - name: Create release
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      run: |
        tag=${{ steps.release-version.outputs.next-version }}

        gh release create "$tag" \
            --repo="$GITHUB_REPOSITORY" \
            --title="v${tag#v}" \
            --generate-notes