name: 'release'
description: 'Creates a Github Release numbered with the latest and the provided commit hash'
inputs:
  GITHUB_TOKEN:
    description: token used to check for existing tags
    required: true

runs:
  using: 'composite'
  steps:
    - name: Clone repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get next version
      id: get_next_version
      uses: thenativeweb/get-next-version@main

    - name: Create release
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        ref: ${{ github.event.push.ref }}
        run: |
          tag=${{ steps.get_next_version.outputs.version }}

          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
              --generate-notes