name: 'release'
description: 'Creates a Github Release numbered with the latest and the provided commit hash'
inputs:
  GITHUB_TOKEN:
    description: token used to check for existing tags
    required: true

runs:
  using: 'composite'
  steps:
    - name: Clone repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get latest release
      id: latest-release
      uses: pozetroninc/github-action-get-latest-release@master
      with:
        repository: 'wishabi/${{ github.event.repository.name }}'

    - name: show latest
      shell: bash
      run: echo ${{ steps.latest-release.outputs.release }}

    #- name: Create release
    #  shell: bash
    #  env:
    #    GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
    #  run: |
    #    tag=${{ steps.release-version.outputs.next-version }}

    #    gh release create "$tag" \
    #        --repo="$GITHUB_REPOSITORY" \
    #        --title="${{steps.release-version.outputs.next-version-name}}" \
    #        --generate-notes