name: "Go Lint"
description: "Lint Go Repo"

inputs:
  FLIPPCIRCLECIPULLER_REPO_TOKEN:
    description: Flipp circleci repo token
    required: true
  BUF_BUILD_USER:
    description: Buf CI user stored as secret
    required: false
  BUF_BUILD_API_TOKEN:
    description: Buf API token stored as secret
    required: false
  SLACK_CHANNEL_ID:
    description: The Slack channel ID(s) to send the data to
    required: false
  SLACK_BOT_TOKEN:
    description: The Slack bot token to pass the data to
    required: false
  GOLANG_CI_LINT_VERSION:
    description: The version of golangci-lint to use
    required: false
    default: ""
  WORKSPACE:
    description: workspace directory
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Set branch variable
      id: set-branch
      shell: bash
      run: |
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          branch="${{ github.event.pull_request.head.ref }}"
        else
          branch="${{ github.ref }}"
          branch="${branch#refs/heads/}"
        fi
        echo "branch=${branch}" >> $GITHUB_OUTPUT
    - name: Get short sha
      id: get-short-sha
      run: echo "short_sha=`echo ${GITHUB_SHA::7}`" > $GITHUB_OUTPUT
      shell: bash
    - name: Configure Go environment
      uses: wishabi/github-actions/go/configure@v0
      with:
        FLIPPCIRCLECIPULLER_REPO_TOKEN: ${{ inputs.FLIPPCIRCLECIPULLER_REPO_TOKEN }}
        BUF_BUILD_USER: ${{ inputs.BUF_BUILD_USER }}
        BUF_BUILD_API_TOKEN: ${{ inputs.BUF_BUILD_API_TOKEN }}
        FETCH_DEPTH: 0
    - name: Setup Go dependencies
      uses: wishabi/github-actions/go/deps@v0
      with:
        FLIPPCIRCLECIPULLER_REPO_TOKEN: ${{ inputs.FLIPPCIRCLECIPULLER_REPO_TOKEN }}
    - name: Setup safe directory
      shell: bash
      run: git config --global --add safe.directory ${{ inputs.WORKSPACE || github.workspace }}
    - name: Determine golangci-lint and config version
      run: |
        # Default to empty version and v1 config
        GOLANGCI_LINT_VERSION=""
        IS_V2="false"
  
        # Check for GOLANG_CI_LINT_VERSION input
        if [ -n "${{ inputs.GOLANG_CI_LINT_VERSION }}" ]; then
          GOLANGCI_LINT_VERSION="${{ inputs.GOLANG_CI_LINT_VERSION }}"
        fi

        # Check .tool-versions if it exists and is not empty
        if [ -z "$GOLANGCI_LINT_VERSION" ] && [ -f ".tool-versions" ] && [ -s ".tool-versions" ]; then
          GOLANGCI_LINT_VERSION=$(awk '/^golangci-lint[[:space:]]+/ {print $2}' .tool-versions) # Extract version directly
        fi

        # Check go.mod for golangci-lint dependency
        if [ -z "$GOLANGCI_LINT_VERSION" ] && [ -f "go.mod" ]; then
          GOLANGCI_LINT_VERSION=$(grep 'golangci/golangci-lint' go.mod | awk '{print $2}')
          # Remove the version comment if it exists
          GOLANGCI_LINT_VERSION=$(echo "$GOLANGCI_LINT_VERSION" | sed 's/\/\/.*//')
        fi

        # Check .golangci.yml for explicit version declaration
        if [ -f ".golangci.yml" ]; then
          if grep -q 'version: "2"' .golangci.yml; then
            IS_V2="true"
          fi
        fi

        # Determine v2 based on version if not explicitly set in .golangci.yml
        if [ "$IS_V2" == "false" ] && [ -n "$GOLANGCI_LINT_VERSION" ]; then
          if [[ "$GOLANGCI_LINT_VERSION" =~ ^v2\..* ]]; then
            IS_V2="true"
          fi
        fi

        echo "IS_V2=${IS_V2}" >> $GITHUB_ENV
        echo "GOLANGCI_LINT_VERSION=${GOLANGCI_LINT_VERSION}" >> $GITHUB_ENV
      shell: bash
    - name: Run v1 Go linter
      if : ${{ steps.golangci_version_config.outputs.IS_V2 == 'false' }}
      uses: golangci/golangci-lint-action@v4
      with:
        skip-cache: true
        args: --verbose
        version: ${{ env.GOLANGCI_LINT_VERSION }} # Optional - if blank, will use the action's default version resolution
    - name: Run v2 Go linter
      if : ${{ steps.golangci_version_config.outputs.IS_V2 == 'true' }}
      uses: golangci/golangci-lint-action@v7 # Note: v7 and up require golangci-lint v2 config
      with:
        skip-cache: true
        args: --verbose
        version: ${{ env.GOLANGCI_LINT_VERSION }} # Optional - if blank, will use the action's default version resolution
    - name: Notify slack channel on failure
      if: failure() && inputs.SLACK_CHANNEL_ID != null && github.ref == 'refs/heads/main'
      uses: slackapi/slack-github-action@v1.24.0
      env:
        SLACK_BOT_TOKEN: ${{ inputs.SLACK_BOT_TOKEN }}
      with:
        channel-id: ${{ inputs.SLACK_CHANNEL_ID }}
        payload: |
          {
            "text": "Go Lint Failed",
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "Go Lint Failed",
                  "emoji": true
                }
              },
              {
                "type": "divider"
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*Repository*\n<https://github.com/${{ github.repository }}|${{ github.repository }}>\n\n*${{ github.event_name == 'pull_request' && 'Pull Request' || 'Branch' }}*\n${{ github.event_name == 'pull_request' && format('<{0}|{1}>', github.event.pull_request.html_url, github.event.pull_request.title) || format('<https://github.com/{0}/commit/{1}|{2}>', github.repository, github.sha, steps.set-branch.outputs.branch)}}"
                },
                "accessory": {
                  "type": "image",
                  "image_url": "https://emoji.slack-edge.com/T02AJQYGN/lint/84d851e0ac2b58c1.png",
                  "alt_text": "lint error icon"
                }
              },
              {
                "type": "divider"
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Version/Commit*"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Event*"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "${{ steps.get-short-sha.outputs.short_sha }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "${{ github.event_name }}"
                  }
                ]
              },
              {
                "type": "context",
                "elements": [
                  {
                    "type": "mrkdwn",
                    "text": "*Triggered By:* ${{ github.triggering_actor }}"
                  }
                ]
              }
            ]
          }
