name: 'go-deps'
description: 'Install dependencies. Optionally runs "buf build" steps when BUF_REPO_NAME is provided'

inputs:
  BUF_REPO_NAME:
    description: Name of the buf repo to be built
    required: false

runs:
  using: 'composite'
  steps:
    - name: Generating protobuf code
      shell: bash
      if: "${{ inputs.BUF_REPO_NAME != '' }}"
      run: buf generate ${{ inputs.BUF_REPO_NAME }}
    - name: Restoring vendor modules from cache
      id: vendor-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: vendor-cache-${{ hashFiles('go.mod','go.sum') }}
        restore-keys: vendor-cache-${{ hashFiles('go.mod','go.sum') }}
    - name: Setting up private modules access
      if: steps.vendor-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        set -e
        git config --global url."https://${{ inputs.FLIPPCIRCLECIPULLER_REPO_TOKEN }}:x-oauth-basic@github.com/wishabi".insteadOf "https://github.com/wishabi"
        # Check that go.mod and go.sum are up to date
        go mod tidy
        git diff --exit-code -- go.mod go.sum
        go mod vendor
    - name: Caching workspace for deploy jobs
      uses: wishabi/github-actions/cache@v0
