name: 'go-deps'
description: 'Install dependencies. Optionally runs "buf build" steps when BUF_REPO_NAME is provided'

inputs:
  BUF_REPO_NAME:
    description: Name of the buf repo to be built
    required: false
  FLIPPCIRCLECIPULLER_REPO_TOKEN:
    description: Flipp circleci repo token
    required: true
  GO_MOD_DIRECTORY:
    description: Directory containing the go.mod and go.sum file
    required: false
    default: .

runs:
  using: 'composite'
  steps:
    - name: Generating protobuf code
      shell: bash
      if: "${{ inputs.BUF_REPO_NAME != '' }}"
      run: buf generate ${{ inputs.BUF_REPO_NAME }}
    - name: Restoring vendor modules from cache
      id: vendor-cache
      uses: actions/cache@v3
      with:
        path: "${{ inputs.GO_MOD_DIRECTORY }}vendor"
        key: vendor-cache-${{ hashFiles(format('{0}go.mod',inputs.GO_MOD_DIRECTORY), format('{0}go.sum',inputs.GO_MOD_DIRECTORY)) }}
        restore-keys: vendor-cache-${{  hashFiles(format('{0}go.mod',inputs.GO_MOD_DIRECTORY), format('{0}go.sum',inputs.GO_MOD_DIRECTORY)) }}
    - name: Setting up private modules access
      if: steps.vendor-cache.outputs.cache-hit != 'true'
      working-directory: ./functions/flipp-accounts-to-user-vault
      shell: bash
      run: |
        set -e
        # Check that go.mod and go.sum are up to date
        go mod tidy
        git diff --exit-code -- go.mod go.sum
        go mod vendor
    - name: Caching workspace for deploy jobs
      uses: wishabi/github-actions/cache@v0
