name: 'go-deps'
description: 'Install dependencies. Optionally runs "buf build" steps when BUF_REPO_NAME is provided'

inputs:
  BUF_REPO_NAME:
    description: Name of the buf repo to be built
    required: false
  FLIPPCIRCLECIPULLER_REPO_TOKEN:
    description: Flipp circleci repo token
    required: true
  GO_MOD_DIRECTORY:
    description: Directory containing the go.mod and go.sum file
    required: false

runs:
  using: 'composite'
  steps:
    - name: Generating protobuf code
      shell: bash
      if: "${{ inputs.BUF_REPO_NAME != '' }}"
      run: buf generate ${{ inputs.BUF_REPO_NAME }}
    - name: Restoring vendor modules from cache
      id: vendor-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: vendor-cache-${{ hashFiles("${{ GO_MOD_DIRECTORY }}go.mod","${{ GO_MOD_DIRECTORY }}go.sum") }}
        restore-keys: vendor-cache-${{  hashFiles("${{ GO_MOD_DIRECTORY }}go.mod","${{ GO_MOD_DIRECTORY }}go.sum") }}
    - name: Setting up private modules access
      if: steps.vendor-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        set -e
        cd ${{ GO_MOD_DIRECTORY }}
        # Check that go.mod and go.sum are up to date
        go mod tidy
        git diff --exit-code -- go.mod go.sum
        go mod vendor
    - name: Caching workspace for deploy jobs
      uses: wishabi/github-actions/cache@v0
