name: 'go-deps'
description: 'Install dependencies. Optionally runs "buf build" steps when BUF_REPO_NAME is provided'

inputs:
  BUF_REPO_NAME:  # Deprecated, leaving for backwards compatibility
    description: DEPRECATED
    required: false
  FLIPPCIRCLECIPULLER_REPO_TOKEN:  # Deprecated, leaving for backwards compatibility
    description: Flipp circleci repo token
    required: false

runs:
  using: 'composite'
  steps:
    - name: Restoring vendor modules from cache
      id: vendor-cache
      uses: actions/cache@v4
      with:
        path: vendor
        key: vendor-cache-${{ hashFiles('go.mod','go.sum') }}
        restore-keys: vendor-cache-${{ hashFiles('go.mod','go.sum') }}
    - name: Generating protobuf code
      if: ${{ hashFiles('buf.gen.yaml') != '' }}
      run: buf generate
      shell: bash
    - name: Setting up private modules access
      if: steps.vendor-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        set -e
        # Check that go.mod and go.sum are up to date
        go mod tidy
        git diff --exit-code -- go.mod go.sum
        go mod vendor
    - name: Run go generate
      run: go generate ./...
      shell: bash
    - name: Grab mockery version
      if: ${{ hashFiles('.tool-versions') != '' }}
      run: |
        MOCKERY_INSTALL_VERSION=$(awk '/^mockery[[:space:]]+/ {print "v"$2}' .tool-versions)
        echo "MOCKERY_INSTALL_VERSION=${MOCKERY_INSTALL_VERSION}" >> $GITHUB_ENV
      shell: bash
    - name: Install mockery
      if: ${{ hashFiles('.mockery.yml') != '' }}
      run: |
        if [ -n "${{ env.MOCKERY_INSTALL_VERSION }}" ]; then
          go install github.com/vektra/mockery/v2@${{ env.MOCKERY_INSTALL_VERSION }}
        else
          go install github.com/vektra/mockery/v2
        fi
      shell: bash
    - name: Generate mocks
      if: ${{ hashFiles('.mockery.yml') != '' }}
      run: mockery
      shell: bash
    - name: Caching workspace for deploy jobs
      uses: wishabi/github-actions/cache@v0
