name: 'lambda-deploy'
description: 'Custom GitHub action that deploys the repository to lambda using its "/deploy/build.sh" script'

inputs:
  ENV:
    description: Application environment (staging or production)
    required: true
  LAMBDA_FUNCTION_DIRECTORY:
    description: Directory containing the lambda function main.go file
    required: false
    default: .

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - name: Cleaning workspace
      shell: bash
      run: shopt -s dotglob && rm -rf "${{ github.workspace }}"/*
    - name: Restoring workspace from cache
      uses: wishabi/github-actions/cache@asdf-support
    - name: Building lambda function for deployment
      shell: bash
      run: |
        go build -o ${{ inputs.LAMBDA_FUNCTION_DIRECTORY }}/main ${{ inputs.LAMBDA_FUNCTION_DIRECTORY }}/main.go
    - name: Deploying to Lambda
      shell: bash
      run: |
        export DEPLOY_ENV=${{ inputs.ENV }}
        chmod +x ./deploy/build.sh && ./deploy/build.sh service
