name: "Buf Update"
description: "Update Buf Dependencies"

inputs:
  BUF_BUILD_USER:
    description: Buf CI user stored as secret
    required: false
  BUF_BUILD_API_TOKEN:
    description: Buf API token stored as secret
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Setting up buf
      uses: bufbuild/buf-setup-action@v1.30.0
      if: "${{ inputs.BUF_BUILD_API_TOKEN != '' }}"
      with:
        github_token: ${{ inputs.FLIPPCIRCLECIPULLER_REPO_TOKEN }}
        buf_user: ${{ inputs.BUF_BUILD_USER }}
        buf_api_token: ${{ inputs.BUF_BUILD_API_TOKEN }}

    - name: Test buf CLI
      shell: bash
      run: buf --version

    - name: Run Buf mod update
      shell: bash
      run: buf mod update
      working-directory: ${{ github.workspace }}/protos

    - name: Check for changes in buf.lock
      shell: bash
      id: check-changes
      run: |
        BUF_LOCK_CHANGES=$(git diff -U0 ${{ github.workspace }}/protos/buf.lock)
        echo "::set-output name=buf-lock-changes::${BUF_LOCK_CHANGES}"

    - name: Extract and create PRs for each change blob
      shell: bash
      if: steps.check-changes.outputs.buf-lock-changes != ''
      run: |
        CHANGES=$(git diff -U0 ${{ github.workspace }}/protos/buf.lock | grep -E "^@@")

        IFS=$'\n'
        for CHANGE in ${CHANGES}; do
          LINE_NUMBERS=$(echo "${CHANGE}" | grep -Po "(^\@\@ -\d+,\d+ \+\d+,\d+ \@\@)")
          LINE_NUMBERS=$(echo "${LINE_NUMBERS}" | awk -F '[-+,]' '{print $2}')

          # Extract the blob of changes for the current range
          CHANGE_BLOB=$(git diff -U0 ${{ github.workspace }}/protos/buf.lock -p | sed -n "/${LINE_NUMBERS}/,/^$/p")

          # Create a temporary branch
          BRANCH_NAME="update-buf-${RANDOM}"
          git checkout -b "${BRANCH_NAME}"

          # Apply the changes to the branch
          echo "${CHANGE_BLOB}" | git apply -

          # Commit the changes
          git add .
          git commit -m "Update Buf dependency"

          # Push the changes to the remote repository
          git push origin "${BRANCH_NAME}"

          # Create a pull request
          gh pr create --base main --head "${BRANCH_NAME}" --title "Update Buf dependency" --body "Automated PR to update Buf dependency."

          # Switch back to the main branch
          git checkout main

          # Delete the temporary branch
          git branch -D "${BRANCH_NAME}"
        done
