name: "Buf Update"
description: "Update Buf Dependencies"

inputs:
  BUF_BUILD_USER:
    description: Buf CI user stored as secret
    required: false
  BUF_BUILD_API_TOKEN:
    description: Buf API token stored as secret
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Setting up buf
      uses: bufbuild/buf-setup-action@v1.30.0
      if: "${{ inputs.BUF_BUILD_API_TOKEN != '' }}"
      with:
        github_token: ${{ inputs.FLIPPCIRCLECIPULLER_REPO_TOKEN }}
        buf_user: ${{ inputs.BUF_BUILD_USER }}
        buf_api_token: ${{ inputs.BUF_BUILD_API_TOKEN }}

    - name: Test buf CLI
      shell: bash
      run: buf --version

    - name: Run Buf mod update
      shell: bash
      run: buf mod update
      working-directory: ${{ github.workspace }}/protos

    - name: Check for changes in buf.lock
      id: check-changes
      shell: bash
      run: |
        echo 'buf-lock-changes<<EOF' >> $GITHUB_OUTPUT
        echo "buf-lock-changes=$(git diff -U0 ${{ github.workspace }}/protos/buf.lock)" >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT

    - name: Extract and create PRs for each change blob
      shell: bash
      env:
        BUF_CHANGES: ${{ steps.check-changes.outputs.buf-lock-changes }}
      run: |
        CHANGES=$(echo ${{ env.BUF_CHANGES }} | grep -E "^@@")

        IFS=$'\n'
        for CHANGE in ${CHANGES}; do
          git reset --hard

          echo $CHANGE
        done
