name: 'tag'
description: 'Creates a tag with the provided name on the provided commit hash'
inputs:
  TAG_NAME:
    description: The name for the tag
    required: true

runs:
  using: 'composite'
  steps:
    - name: SonarQube Scan
      shell: bash
      run: |
        export PATH=/home/circleci/_work/sonar-scanner/bin:$PATH
        echo \
          github.rest.git.createRef({ \
            owner: context.repo.owner, \
            repo: context.repo.repo, \
            ref: 'refs/tags/${{ inputs.TAG_NAME }}', \
            sha: '${{ github.sha }}'' \
          })
    - name: Create tag
      uses: actions/github-script@v5
      with:
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: 'refs/tags/${{ inputs.TAG_NAME }}',
            sha: '${{ github.sha }}''
          })