name: 'tag'
description: 'Creates a tag with the provided name on the provided commit hash'
inputs:
  GITHUB_TOKEN:
    description: token used to check for existing tags
    required: true

runs:
  using: 'composite'
  steps:
    - name: Auto Increment Semver Action
      uses: MCKanpolat/auto-semver-action@v1
      id: versioning
      with:
        releaseType: patch
        incrementPerCommit: false
        github_token: ${{ inputs.GITHUB_TOKEN }}

    - name: Next Release Number
      shell: bash
      run: echo ${{ steps.versioning.outputs.version }}

    - name: Create tag
      uses: actions/github-script@v5
      with:
        script: |
          github.rest.git.createRef({ owner: context.repo.owner, repo: context.repo.repo, ref: 'refs/tags/${{ steps.versioning.outputs.version }}', sha: '${{ github.sha }}' })