name: 'Lint - rubocop'
description: 'Lints using rubocop'

runs:
  using: "composite"
  steps:
    - name: Execute rubocop
      id: rubocop
      continue-on-error: true
      shell: bash
      run: |
        bundle exec rubocop --format progress --format json --out rubocop/rubocop.json
        EXIT_CODE="$?"
        echo "exit-code=$(echo $EXIT_CODE)" >> $GITHUB_OUTPUT
      env: 
        BUNDLE_DEPLOYMENT: true
    - name: 'Upload rubocop results'
      uses: actions/upload-artifact@v3
      with:
        name: "${{ github.sha }}-lint-results.out"
        path: ./rubocop/rubocop.json
        retention-days: 1
    - name:
      shell: bash
      run: exit "${{ steps.rubocop.outputs.exit-code }}"
