name: 'Lint - rubocop'
description: 'Lints using rubocop'

inputs:
  CONTINUE_ON_ERROR:
    description: whether to continue on error from linter
    required: true

runs:
  using: "composite"
  steps:
    - name: Execute rubocop
      # Currently always string (use or in case this changes) https://github.com/actions/runner/issues/2238
      continue-on-error: ${{ inputs.CONTINUE_ON_ERROR == 'true' || inputs.CONTINUE_ON_ERROR == true }} 
      shell: bash
      run: bundle exec rubocop --format progress --format json --out rubocop/rubocop.json
    - name: 'Upload rubocop results'
      uses: actions/upload-artifact@v3
      with:
        name: "${{ github.sha }}-lint-results.out"
        path: ./rubocop/rubocop.json
        retention-days: 1
