name: 'SonarQube Quality Scan'
description: 'Runs various quality and security checks against changes'
inputs:
  SONAR_HOST_URL:
    description: secret value
    required: true
  SONAR_TOKEN:
    description: secret value
    required: true
  CHECK_RUBOCOP:
    description: whether to download and analyze rubocop results
    default: false
runs:
  using: "composite"
  steps:
    - uses: rlespinasse/github-slug-action@v3.x
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Downloading coverage
      uses: actions/download-artifact@v3
      with:
        name: "${{ github.sha }}-coverage.out"
    - name: Download rubocop results
      if: ${{ inputs.CHECK_RUBOCOP == 'true' }}
      uses: actions/download-artifact@v3
      with:
        name: ${{ github.sha }}-rubocop-results
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ inputs.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ inputs.SONAR_HOST_URL }}
      args: >
        -Dsonar.projectVersion=${GITHUB_SHA::7}
