name: 'SonarQube Quality Scan'
description: 'Runs various quality and security checks against changes'
inputs:
  FLIPPCIRCLECIPULLER_REPO_TOKEN:
    description: secret value
    required: true
  SONAR_HOST_URL:
    description: secret value
    required: true
  SONAR_TOKEN:
    description: secret value
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup private modules access
      run: git config --global url."https://${{ inputs.FLIPPCIRCLECIPULLER_REPO_TOKEN }}:x-oauth-basic@github.com/wishabi".insteadOf "https://github.com/wishabi"
      shell: bash
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '1.19'
        check-latest: true
        cache: true
    - name: Download test report
      uses: actions/download-artifact@v3
      with:
        name: "${{ github.sha }}-test-report.out"
    - name: Download coverage
      uses: actions/download-artifact@v3
      with:
        name: "${{ github.sha }}-coverage.out"
    - name: SonarQube Scan
      shell: bash
      run: |
          export PATH=/home/circleci/_work/sonar-scanner/bin:$PATH
          sonar-scanner \
           -Dsonar.projectVersion=${GITHUB_SHA::7} \
           -Dsonar.host.url=${{ inputs.SONAR_HOST_URL }} \
           -Dsonar.login=${{ inputs.SONAR_TOKEN }}