name: 'SonarQube Quality Scan'
description: 'Runs various quality and security checks against changes'
inputs:
  SONAR_HOST_URL:
    description: secret value
    required: true
  SONAR_TOKEN:
    description: secret value
    required: true
  CHECK_COVERAGE:
    description: whether to download and analyze linter results
  CHECK_LINTER:
    description: whether to download and analyze linter results
    default: false
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Downloading test report
      uses: actions/download-artifact@v3
      with:
        name: "${{ github.sha }}-test-report.out"
    - name: Downloading coverage report
      uses: actions/download-artifact@v3
      with:
        name: "${{ github.sha }}-coverage.out"
    - name: Download linter results
      if: ${{ inputs.CHECK_LINTER == 'true' }}
      uses: actions/download-artifact@v3
      with:
        name: ${{ github.sha }}-linter-results.out
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ inputs.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ inputs.SONAR_HOST_URL }}
      with:
        args: >
          -Dsonar.projectVersion=${GITHUB_SHA::7}
