name: Update Main Version
run-name: Move ${{ github.event.inputs.major_version }} to ${{ github.event.inputs.target }}

on:
  workflow_dispatch:
    inputs:
      target:
        description: The tag or reference to use
        required: true
      major_version:
        type: choice
        description: The major version to update
        options:
          - v0

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - name: Git config
      run: |
        git config user.name flipp-bot
        git config user.email flipp-bot@flipp.com
    - name: Tag new target
      env:
        MAJOR_VERSION: ${{ github.event.inputs.major_version }}
        TARGET_REF: ${{ github.event.inputs.target }}
      run: git tag -f "$MAJOR_VERSION" "$TARGET_REF"
    - name: Push new tag
      env:
        MAJOR_VERSION: ${{ github.event.inputs.major_version }}
      run: git push origin "$MAJOR_VERSION" --force
