name: Secret Scan

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

jobs:
  secret-scan:
    uses: wishabi/github-shared-actions/.github/workflows/secret-scan.yml@main
    secrets: inherit
