name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: [ ubuntu, runner-fleet ]
    container:
      image: ghcr.io/wishabi/ci-build-environment:node-16-browsers
      credentials:
        username: "${{ github.repository_owner }}"
        password: "${{ secrets.GHCR_TOKEN }}"
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test

  # test action works running from the graph
  test:
    runs-on: [ ubuntu, runner-fleet ]
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        milliseconds: 1000
